DROP PROCEDURE IF EXISTS sp_fillHourReference $$
CREATE PROCEDURE sp_fillHourReference ()
BEGIN
INSERT INTO hour VALUES(0);
INSERT INTO hour VALUES(1);
INSERT INTO hour VALUES(2);
INSERT INTO hour VALUES(3);
INSERT INTO hour VALUES(4);
INSERT INTO hour VALUES(5);
INSERT INTO hour VALUES(6);
INSERT INTO hour VALUES(7);
INSERT INTO hour VALUES(8);
INSERT INTO hour VALUES(9);
INSERT INTO hour VALUES(10);
INSERT INTO hour VALUES(11);
INSERT INTO hour VALUES(12);
INSERT INTO hour VALUES(13);
INSERT INTO hour VALUES(14);
INSERT INTO hour VALUES(15);
INSERT INTO hour VALUES(16);
INSERT INTO hour VALUES(17);
INSERT INTO hour VALUES(18);
INSERT INTO hour VALUES(19);
INSERT INTO hour VALUES(20);
INSERT INTO hour VALUES(21);
INSERT INTO hour VALUES(22);
INSERT INTO hour VALUES(23);
END $$
